[tool.black]
line-length = 100
target-version = ["py312"]
exclude = '''
/(
  \.venv
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | migrations
)/
'''

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = ["migrations", ".venv", ".git"]
select = ["E","F","I","UP"]
ignore = []

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "LibraryPro.settings.dev"
python_files = ["tests.py", "test_*.py", "*_tests.py"]