# Generated by Django 5.1.11 on 2025-08-17 01:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("loan_date", models.DateField(default=django.utils.timezone.localdate)),
                ("due_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("RETURNED", "Devuelto"),
                            ("LATE", "Atrasado"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="catalog.book",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="accounts.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "préstamo",
                "verbose_name_plural": "préstamos",
                "ordering": ["-loan_date"],
            },
        ),
    ]
