# Generated by Django 5.1.11 on 2025-08-17 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=150)),
                ("isbn", models.CharField(max_length=20, unique=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("copies_total", models.PositiveIntegerField(default=1)),
                ("copies_available", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "libro",
                "verbose_name_plural": "libros",
                "ordering": ["title"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("copies_available__gte", 0)),
                        name="book_copies_available_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("copies_available__lte", models.F("copies_total"))),
                        name="book_copies_available_le_total",
                    ),
                ],
            },
        ),
    ]
